# Numpy

In [1]:
import numpy as np

In [13]:
myarr = np.array([[3,6,32,7]],np.int64)

In [14]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [17]:
myarr[0,1]

6

In [18]:
myarr.shape

(1, 4)

In [19]:
myarr.dtype

dtype('int64')

In [21]:
myarr[0,1]

6

In [22]:
myarr[0,1]=45

In [23]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

## Array Creation: Conversion from other Python Structures

In [25]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [27]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [28]:
listarray.dtype

dtype('int32')

In [29]:
listarray.shape

(3, 3)

In [30]:
listarray.size

9

In [31]:
zeros=np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.dtype

dtype('float64')

In [35]:
rng=np.arange(15)

In [36]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
 lspace=np.linspace(0,100,4)

In [54]:
lspace

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [57]:
emp=np.empty((2,3))

In [58]:
emp

array([[  1. ,  20.8,  40.6],
       [ 60.4,  80.2, 100. ]])

In [59]:
emp_like=np.empty_like(lspace)

In [60]:
emp_like

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [61]:
ide=np.identity(45)

In [62]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
ide.shape

(45, 45)

In [64]:
arr=np.arange(99)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [72]:
arr=arr.reshape(33,3)

In [73]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [75]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [76]:
arr.shape

(99,)

In [77]:
  x=[[1,2,3],[4,5,6],[7,8,9]]

In [78]:
ar=np.array(x)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
ar.sum(axis=0)

array([12, 15, 18])

In [81]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [91]:
ar.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
ar.flat

In [104]:
for item in ar.flat:
    print(item)

1
4
7
2
5
8
3
6
9


In [105]:
ar.ndim

2

In [106]:
ar.dtype

dtype('int32')

In [107]:
ar.nbytes

36

In [108]:
ar.size

9

In [109]:
one=np.array([1,3,4,634,2])

In [101]:
one.argmax()

3

In [110]:
one[3]

634

In [112]:
one[one.argmax()]

634

In [113]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [114]:
one

array([  1,   3,   4, 634,   2])

In [116]:
one[one.argsort()]

array([  1,   2,   3,   4, 634])

In [117]:
ar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [118]:
ar=ar.T

In [119]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
ar[2,2]=0

In [121]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [122]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [123]:
ar.argmin()

8

In [124]:
ar.argmax()

7

In [125]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [126]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [127]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [128]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [129]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [130]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [131]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  0]])

In [132]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [136]:
print(ar)
print(ar2)
print(ar*ar2)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 2 1]
 [4 0 6]
 [8 1 0]]
[[ 1  4  3]
 [16  0 36]
 [56  8  0]]


In [137]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [141]:
np.sqrt(324)

18.0

In [142]:
 ar.sum()

36

In [145]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [146]:
import sys

In [149]:
py_ar=[0,4,55,2]

In [150]:
np_ar=np.array(py_ar)

In [151]:
np_ar

array([ 0,  4, 55,  2])

In [152]:
sys.getsizeof(1)*len(py_ar)

112

In [154]:
np_ar.itemsize*np_ar.size

16

## Numpy Random Module

In [155]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [185]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[78 50 85]


In [165]:
a=np.random.randn(2,3)
print(a)

a=np.random.randint(50,100,3)
print(a)

[[-0.54460865 -0.18467004 -0.75074538]
 [ 1.05927602 -1.15668124 -1.57449012]]
[50 78 85]


In [168]:
element=np.random.choice([1,2,3,4,5,0,9,8])
print(element)

4


## Some More NUmpy Functions - Statistics 
- min,max
- mean
- median
- average
- variance
- standard devidation

In [186]:
a=np.array([[1,2,3,4],[7,6,2,0]])

In [187]:
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [188]:
print(np.min(a))

0


In [189]:
print(np.min(a,axis=0))

[1 2 2 0]


In [190]:
b=np.array([1,2,3,4,5])
m=sum(b)/len(b)
print(m)
print(np.mean(b))

3.0
3.0


In [191]:
print(np.mean(a,axis=1))

[2.5  3.75]


In [201]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))
w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.0
2.4
2.066666666666667
