# Working with Numpy - for mathematical opeqations

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [5]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [12]:
# Create zeroes, Ones, Custom array
a = np.zeros((3,3))
print(a)

b=np.ones((2,3))
print(b)


# Array of some constants

c=np.full((3,2),5)
print(c)

# Identity Matrix - Size/Sqaure matrix
d=np.eye(4)
print(d)

# Random array
randommatrix=np.random.random((2,3))
print(randommatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.67575736 0.28653346 0.46774404]
 [0.74879968 0.66348833 0.09800095]]


In [13]:
print(randommatrix[:,1])

[0.28653346 0.66348833]


In [21]:
randommatrix[1,1:3]=1
print(randommatrix)

[[0.67575736 0.28653346 0.46774404]
 [0.74879968 1.         1.        ]]


In [44]:
# Set some rows and columns with any values
z=np.zeros((3,3))
z[1,:]=5
z[:,2]=7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]
